apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-resource-visualizer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-resource-visualizer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "k8s-resource-visualizer.selectorLabels" . | nindent 4 }}
